/*  
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.cntt.lab03;

import dao.DangKy;
import dao.DangKyDao;
import dao.Khoa;
import dao.KhoaDao;
import dao.MonHoc;
import dao.MonHocDao;

import dao.SinhVien;
import dao.SinhVienDao;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI
 */
public class SinhVienForm extends javax.swing.JFrame {

    SinhVienDao sinhVienDao = new SinhVienDao();
    KhoaDao khoaDao = new KhoaDao();
    MonHocDao monHocDao = new MonHocDao();
    DangKyDao dangKyDao = new DangKyDao();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SinhVienForm.class.getName());

    /**
     * Creates new form SinhVienForm
     */
    public SinhVienForm() {

        initComponents();
        Khoi_Tao_Table();
        Khoi_Tao_ComboBox();
        Gan_Du_lieu();

        //khoa
        Khoi_Tao_TableKH();
        Gan_Du_LieuKH();

        //môn học
        Khoi_Tao_TableMH();
        Gan_Du_LieuMH();

        //đăng ký
        Khoi_Tao_TableDK();
        Gan_Du_LieuDK();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGioiTinh = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabSinhVien = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        dtcNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        radNam = new javax.swing.JRadioButton();
        RadNu = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        cboKhoa = new javax.swing.JComboBox<>();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        tabKhoa = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        btnThoatKH = new javax.swing.JButton();
        btnThemKH = new javax.swing.JButton();
        btnSuaKH = new javax.swing.JButton();
        btnXoaKH = new javax.swing.JButton();
        btnLamMoiKH = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKhoa = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        tabmonhoc = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtMaMH = new javax.swing.JTextField();
        txtTenMH = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtstc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnThemMH = new javax.swing.JButton();
        btnXoaMH = new javax.swing.JButton();
        btnSuaMH = new javax.swing.JButton();
        btnLamMoiMH = new javax.swing.JButton();
        btnThoatMH = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblMonHoc = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        tabDangKy = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtMaMHDK = new javax.swing.JTextField();
        txtMaSVDK = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDiemQT = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnThemDK = new javax.swing.JButton();
        btnXoaDK = new javax.swing.JButton();
        btnSuaDK = new javax.swing.JButton();
        btnLamMoiDK = new javax.swing.JButton();
        btnThoatDK = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtDiemThi = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtDiemTK = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        dtcNgayDK = new com.toedter.calendar.JDateChooser();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDangKy = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("QUẢN LÝ SINH VIÊN");
        setBackground(new java.awt.Color(204, 204, 204));
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 204));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tabSinhVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Sinh Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mã Sinh Viên:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 31, 91, -1));

        txtMaSV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMaSV.addActionListener(this::txtMaSVActionPerformed);
        jPanel1.add(txtMaSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 28, 254, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Ngày Sinh:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 64, 91, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Địa Chỉ:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 104, 91, -1));

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 101, 295, -1));
        jPanel1.add(dtcNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 61, 254, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Họ Tên:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 31, 91, -1));

        txtHoTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtHoTen.setText("Nguyễn Thái Hưng");
        txtHoTen.addActionListener(this::txtHoTenActionPerformed);
        jPanel1.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 28, 318, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Giới Tính:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 64, 91, -1));

        btgGioiTinh.add(radNam);
        radNam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radNam.setText("Nam");
        jPanel1.add(radNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 62, 98, -1));

        btgGioiTinh.add(RadNu);
        RadNu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadNu.setText("Nữ");
        jPanel1.add(RadNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 62, 98, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Khoa:");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 104, 91, -1));

        cboKhoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cboKhoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 101, 318, -1));

        tabSinhVien.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 880, 140));

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pen.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSua.setIconTextGap(10);
        btnSua.addActionListener(this::btnSuaActionPerformed);
        tabSinhVien.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 145, 44));

        btnLamMoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reload.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLamMoi.setIconTextGap(10);
        btnLamMoi.addActionListener(this::btnLamMoiActionPerformed);
        tabSinhVien.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 145, 44));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThem.setIconTextGap(10);
        btnThem.addActionListener(this::btnThemActionPerformed);
        tabSinhVien.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 145, 44));

        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThoat.setIconTextGap(10);
        btnThoat.addActionListener(this::btnThoatActionPerformed);
        tabSinhVien.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 146, 44));

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnXoa.setIconTextGap(10);
        btnXoa.addActionListener(this::btnXoaActionPerformed);
        tabSinhVien.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 145, 44));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Sinh Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 204)))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSinhVien.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sinh Viên", "Họ Tên", "Ngày Sinh", "Giới Tính", "Địa Chỉ", "Mã Khoa"
            }
        ));
        tblSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSinhVien);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 860, 160));

        tabSinhVien.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 880, 180));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ahnennn.jpg"))); // NOI18N
        tabSinhVien.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 910, 510));

        jTabbedPane1.addTab("Sinh Viên", new javax.swing.ImageIcon(getClass().getResource("/icons/graduating-student.png")), tabSinhVien); // NOI18N

        tabKhoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabKhoa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Khoa ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel5.setAlignmentX(0.0F);
        jPanel5.setAlignmentY(0.0F);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tên Khoa:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 81, -1, 20));
        jPanel5.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 210, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Mã Khoa:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 43, -1, -1));
        jPanel5.add(txtMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 210, -1));

        btnThoatKH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThoatKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        btnThoatKH.setText("Thoát");
        btnThoatKH.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThoatKH.setIconTextGap(10);
        btnThoatKH.addActionListener(this::btnThoatKHActionPerformed);
        jPanel5.add(btnThoatKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 114, -1));

        btnThemKH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        btnThemKH.setText("Thêm");
        btnThemKH.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThemKH.setIconTextGap(10);
        btnThemKH.addActionListener(this::btnThemKHActionPerformed);
        jPanel5.add(btnThemKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 114, -1));

        btnSuaKH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuaKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pen.png"))); // NOI18N
        btnSuaKH.setText("Sửa");
        btnSuaKH.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSuaKH.setIconTextGap(10);
        btnSuaKH.addActionListener(this::btnSuaKHActionPerformed);
        jPanel5.add(btnSuaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 114, -1));

        btnXoaKH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btnXoaKH.setText("Xóa");
        btnXoaKH.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnXoaKH.setIconTextGap(10);
        btnXoaKH.addActionListener(this::btnXoaKHActionPerformed);
        jPanel5.add(btnXoaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 114, -1));

        btnLamMoiKH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLamMoiKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reload.png"))); // NOI18N
        btnLamMoiKH.setText("Làm Mới");
        btnLamMoiKH.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLamMoiKH.setIconTextGap(10);
        btnLamMoiKH.addActionListener(this::btnLamMoiKHActionPerformed);
        jPanel5.add(btnLamMoiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        tabKhoa.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 850, 140));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Khoa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblKhoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblKhoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Khoa", "Tên Khoa"
            }
        ));
        tblKhoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhoaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKhoa);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 850, 180));

        tabKhoa.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 850, 220));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ahnennn.jpg"))); // NOI18N
        tabKhoa.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 490));

        jTabbedPane1.addTab("Khoa", new javax.swing.ImageIcon(getClass().getResource("/icons/graduation.png")), tabKhoa); // NOI18N

        tabmonhoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Môn Học", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Mã Môn Học:");

        txtMaMH.addActionListener(this::txtMaMHActionPerformed);

        txtTenMH.addActionListener(this::txtTenMHActionPerformed);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Tên Môn Học:");

        txtstc.setBackground(new java.awt.Color(0, 0, 255));
        txtstc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtstc.setForeground(new java.awt.Color(255, 255, 255));
        txtstc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtstc.setText("0");
        txtstc.addActionListener(this::txtstcActionPerformed);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Số Tín Chỉ");

        btnThemMH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        btnThemMH.setText("Thêm");
        btnThemMH.addActionListener(this::btnThemMHActionPerformed);

        btnXoaMH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btnXoaMH.setText("Xóa");
        btnXoaMH.addActionListener(this::btnXoaMHActionPerformed);

        btnSuaMH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuaMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pen.png"))); // NOI18N
        btnSuaMH.setText("Sửa");
        btnSuaMH.addActionListener(this::btnSuaMHActionPerformed);

        btnLamMoiMH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLamMoiMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reload.png"))); // NOI18N
        btnLamMoiMH.setText("Làm Mới");
        btnLamMoiMH.addActionListener(this::btnLamMoiMHActionPerformed);

        btnThoatMH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThoatMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        btnThoatMH.setText("Thoát");
        btnThoatMH.addActionListener(this::btnThoatMHActionPerformed);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenMH, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel13))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtstc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnThemMH, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSuaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnLamMoiMH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThoatMH, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLamMoiMH, btnSuaMH, btnThemMH, btnThoatMH, btnXoaMH});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(txtMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(btnSuaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnXoaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnThemMH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnThoatMH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLamMoiMH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(3, 3, 3)
                            .addComponent(txtstc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );

        tabmonhoc.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 860, 140));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Môn Học", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblMonHoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TblMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Môn Học", "Tên Môn Học", "Số Tín Chỉ"
            }
        ));
        TblMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblMonHocMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TblMonHoc);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 27, 850, 190));

        tabmonhoc.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 240));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ahnennn.jpg"))); // NOI18N
        tabmonhoc.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        jTabbedPane1.addTab("Môn Học", new javax.swing.ImageIcon(getClass().getResource("/icons/books.png")), tabmonhoc); // NOI18N

        tabDangKy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Đăng Ký", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Mã Môn Học:");

        txtMaMHDK.addActionListener(this::txtMaMHDKActionPerformed);

        txtMaSVDK.addActionListener(this::txtMaSVDKActionPerformed);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Mã Sinh Viên:");

        txtDiemQT.setBackground(new java.awt.Color(0, 0, 0));
        txtDiemQT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDiemQT.setForeground(new java.awt.Color(255, 255, 255));
        txtDiemQT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiemQT.setText("0");
        txtDiemQT.addActionListener(this::txtDiemQTActionPerformed);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Điểm Quá Trình:");

        btnThemDK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemDK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        btnThemDK.setText("Đăng Ký");
        btnThemDK.addActionListener(this::btnThemDKActionPerformed);

        btnXoaDK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaDK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btnXoaDK.setText("Xóa");
        btnXoaDK.addActionListener(this::btnXoaDKActionPerformed);

        btnSuaDK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuaDK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pen.png"))); // NOI18N
        btnSuaDK.setText("Sửa");
        btnSuaDK.addActionListener(this::btnSuaDKActionPerformed);

        btnLamMoiDK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLamMoiDK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reload.png"))); // NOI18N
        btnLamMoiDK.setText("Làm Mới");
        btnLamMoiDK.addActionListener(this::btnLamMoiDKActionPerformed);

        btnThoatDK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThoatDK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        btnThoatDK.setText("Thoát");
        btnThoatDK.addActionListener(this::btnThoatDKActionPerformed);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Điểm Thi:");

        txtDiemThi.setBackground(new java.awt.Color(0, 0, 255));
        txtDiemThi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDiemThi.setForeground(new java.awt.Color(255, 255, 255));
        txtDiemThi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiemThi.setText("0");
        txtDiemThi.addActionListener(this::txtDiemThiActionPerformed);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Điểm Tổng Kết:");

        txtDiemTK.setBackground(new java.awt.Color(255, 0, 8));
        txtDiemTK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDiemTK.setForeground(new java.awt.Color(255, 255, 255));
        txtDiemTK.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiemTK.setText("0");
        txtDiemTK.addActionListener(this::txtDiemTKActionPerformed);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Ngày Đăng Ký:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtcNgayDK, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtMaSVDK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addComponent(txtMaMHDK, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiemQT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiemThi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(btnThemDK, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXoaDK, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSuaDK, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLamMoiDK)
                                .addGap(18, 18, 18)
                                .addComponent(btnThoatDK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDiemQT, txtDiemThi});

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLamMoiDK, btnSuaDK, btnThemDK, btnThoatDK, btnXoaDK});

        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(txtDiemThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDiemQT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDiemTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMaMHDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(dtcNgayDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(btnSuaDK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXoaDK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThemDK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnLamMoiDK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThoatDK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtMaSVDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tabDangKy.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 860, 160));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Đăng Ký", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDangKy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblDangKy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sinh Viên", "Mã Môn", "Ngày Đăng Ký", "Điểm Quá Trình", "Điểm Thi", "Điểm Tổng Kết"
            }
        ));
        tblDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDangKyMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDangKy);

        jPanel10.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 27, 860, 180));

        tabDangKy.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 860, 220));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ahnennn.jpg"))); // NOI18N
        tabDangKy.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        jTabbedPane1.addTab("Đăng Ký", new javax.swing.ImageIcon(getClass().getResource("/icons/contract.png")), tabDangKy); // NOI18N

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        //  Kiểm tra các ô Text rỗng
        if (txtMaSV.getText().trim().isEmpty() || txtHoTen.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ Mã SV và Họ tên!");
            return; // Dừng hàm ngay lập tức
        }

        //  Kiểm tra Ngày sinh rỗng 
        if (dtcNgaySinh.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Ngày sinh!");
            return; // Dừng hàm
        }

        //Kiểm tra ComboBox Khoa
        if (cboKhoa.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Khoa!");
            return; // Dừng hàm
        }

        // Nếu tất cả đều hợp lệ mới tạo đối tượng và chèn vào CSDL
        SinhVien sv = Gan_Du_lieu();

        if (sinhVienDao.insert(sv)) {
            JOptionPane.showMessageDialog(this, "Thêm sinh viên thành công!");
            Khoi_Tao_Table();
            btnLamMoiActionPerformed(null);
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại! Mã sinh viên có thể đã tồn tại.");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        txtMaSV.setText("");
        txtHoTen.setText("");
        txtDiaChi.setText("");
        dtcNgaySinh.setDate(null);
        radNam.setSelected(true);
        if (cboKhoa.getItemCount() > 0) {
            cboKhoa.setSelectedIndex(0);
        }

        // Bỏ chọn dòng trên 
        tblSinhVien.clearSelection();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

        String maSV = txtMaSV.getText().trim();
        String tenSV = txtHoTen.getText().trim();

        int chi_so_dong = tblSinhVien.getSelectedRow();
        if (chi_so_dong < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần xóa trên bảng!");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn xóa sinh viên: [" + maSV + " - " + tenSV + "]" + " không?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            if (sinhVienDao.delete(maSV)) {
                JOptionPane.showMessageDialog(this, "Xóa sinh viên thành công!");
                Khoi_Tao_Table();
                btnLamMoiActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
    }//GEN-LAST:event_btnXoaActionPerformed
    }
    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn thoát chương trình không?",
                "Xác nhận Thoát",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
    }//GEN-LAST:event_btnThoatActionPerformed
    }
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int chi_so_dong = tblSinhVien.getSelectedRow();
        String maSV = txtMaSV.getText().trim();
        if (chi_so_dong < 0 && maSV.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa hoặc nhập Mã Sinh Viên để Sửa!");
            return;
        }

        SinhVien sv = Gan_Du_lieu();

        if (sinhVienDao.update(sv)) {
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công!");
            Khoi_Tao_Table();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhVienMouseClicked
        int row = tblSinhVien.getSelectedRow();

        if (row >= 0) {

            String maSV = tblSinhVien.getValueAt(row, 0).toString();
            String hoTen = tblSinhVien.getValueAt(row, 1).toString();
            String strNgay = tblSinhVien.getValueAt(row, 2).toString();
            String gioiTinh = tblSinhVien.getValueAt(row, 3).toString();
            String diaChi = tblSinhVien.getValueAt(row, 4) != null ? tblSinhVien.getValueAt(row, 4).toString() : "";
            String maKhoa = tblSinhVien.getValueAt(row, 5).toString();

            txtMaSV.setText(maSV);
            txtHoTen.setText(hoTen);
            txtDiaChi.setText(diaChi);

            //  Set giá trị cho RadioButton (Giới tính)
            if (gioiTinh.equalsIgnoreCase("Nam")) {
                radNam.setSelected(true);
            } else {
                RadNu.setSelected(true);
            }

            //chuyển đổi kiểu ngày tháng
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                Date ngaySinh = sdf.parse(strNgay);
                dtcNgaySinh.setDate(ngaySinh);
            } catch (Exception e) {
                dtcNgaySinh.setDate(null);
            }

            // 6. Set giá trị cho ComboBox Khoa
            Chon_Khoa(maKhoa);
    }//GEN-LAST:event_tblSinhVienMouseClicked
    }
    private void btnXoaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKHActionPerformed

        int chi_so_dong = tblKhoa.getSelectedRow();
        if (chi_so_dong < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần xóa trên bảng!");
            return;
        }

        String maKH = tblKhoa.getValueAt(chi_so_dong, 0).toString().trim();

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn xóa khoa: [" + maKH + "] không?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            if (khoaDao.delete(maKH)) {
                JOptionPane.showMessageDialog(this, "Xóa KHOA thành công!");
                Khoi_Tao_TableKH();
                btnLamMoiActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        }
    }//GEN-LAST:event_btnXoaKHActionPerformed

    private void tblKhoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhoaMouseClicked
        int row = tblKhoa.getSelectedRow();

        if (row >= 0) {

            String maKH = tblKhoa.getValueAt(row, 0).toString();
            String TenKH = tblKhoa.getValueAt(row, 1).toString();

            txtMaKH.setText(maKH);
            txtTenKH.setText(TenKH);


    }//GEN-LAST:event_tblKhoaMouseClicked
    }
    private void btnThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKHActionPerformed
        //  Kiểm tra các ô Text rỗng
        if (txtMaKH.getText().trim().isEmpty() || txtTenKH.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ Mã Khoa và Tên Khoa!");
            return; // Dừng hàm ngay lập tức
        }

        //  Kiểm tra Ngày sinh rỗng 
        // Nếu tất cả đều hợp lệ mới tạo đối tượng và chèn vào CSDL
        Khoa kh = Gan_Du_LieuKH();

        if (khoaDao.insert(kh)) {
            JOptionPane.showMessageDialog(this, "Thêm Khoa thành công!");
            Khoi_Tao_TableKH();
            btnLamMoiActionPerformed(null);
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại! Mã Khoa có thể đã tồn tại.");
        }
    }//GEN-LAST:event_btnThemKHActionPerformed

    private void btnSuaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKHActionPerformed
        int chi_so_dong = tblKhoa.getSelectedRow();
        String maKH = txtMaKH.getText().trim();
        if (chi_so_dong < 0 && maKH.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa hoặc nhập Mã Khoa để Sửa!");
            return;
        }

        Khoa kh = Gan_Du_LieuKH();

        if (khoaDao.update(kh)) {
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin Khoa thành công!");
            Khoi_Tao_TableKH();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
        }
    }//GEN-LAST:event_btnSuaKHActionPerformed

    private void btnLamMoiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiKHActionPerformed
        txtMaKH.setText("");
        txtTenKH.setText("");

        tblKhoa.clearSelection();
    }//GEN-LAST:event_btnLamMoiKHActionPerformed

    private void btnThoatKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatKHActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn thoát chương trình không?",
                "Xác nhận Thoát",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnThoatKHActionPerformed

    private void txtMaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSVActionPerformed

    private void txtMaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMHActionPerformed

    private void txtTenMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenMHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenMHActionPerformed

    private void txtstcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstcActionPerformed

    private void txtMaMHDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMHDKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMHDKActionPerformed

    private void txtMaSVDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSVDKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSVDKActionPerformed

    private void txtDiemQTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemQTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemQTActionPerformed

    private void txtDiemThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemThiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemThiActionPerformed

    private void txtDiemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemTKActionPerformed

    private void btnSuaDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDKActionPerformed
        int chi_so_dong = tblDangKy.getSelectedRow();
        String maSV = txtMaSVDK.getText().trim();
    String maMH = txtMaMHDK.getText().trim();

    if (chi_so_dong < 0 && (maSV.isEmpty() || maMH.isEmpty())) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa hoặc nhập đủ Mã SV và Mã Môn Học!");
        return;
    }

        DangKy dk = Gan_Du_LieuDK();

        if (dangKyDao.update(dk)) {
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công!");
            Khoi_Tao_TableDK();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
        }
    }//GEN-LAST:event_btnSuaDKActionPerformed

    private void btnXoaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMHActionPerformed
        int chi_so_dong = TblMonHoc.getSelectedRow();
        String maSV = txtMaSV.getText().trim();
        if (chi_so_dong < 0 && maSV.isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng hoặc nhập Mã sinh viên cần Xóa !");
            return;
        }

        String maMH = TblMonHoc.getValueAt(chi_so_dong, 0).toString().trim();
        String TenMH = TblMonHoc.getValueAt(chi_so_dong, 0).toString().trim();

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn xóa Môn Học: [" + maMH + "] không?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            if (monHocDao.delete(maMH)) {
                JOptionPane.showMessageDialog(this, "Xóa MÔN thành công!");
                Khoi_Tao_TableMH();
                btnLamMoiActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        }
    }//GEN-LAST:event_btnXoaMHActionPerformed

    private void btnThoatMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatMHActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn thoát chương trình không?",
                "Xác nhận Thoát",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnThoatMHActionPerformed

    private void btnThoatDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatDKActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn thoát chương trình không?",
                "Xác nhận Thoát",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnThoatDKActionPerformed

    private void btnLamMoiMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiMHActionPerformed
        txtMaMH.setText("");
        txtTenMH.setText("");
        txtstc.setText("");
        TblMonHoc.clearSelection();
    }//GEN-LAST:event_btnLamMoiMHActionPerformed

    private void btnLamMoiDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiDKActionPerformed
        txtMaSVDK.setText("");
        txtMaMHDK.setText("");
        txtDiemQT.setText("");
        txtDiemThi.setText("");
        txtDiemTK.setText("");
        dtcNgayDK.setDate(null);
        tblDangKy.clearSelection();

    }//GEN-LAST:event_btnLamMoiDKActionPerformed

    private void btnThemMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMHActionPerformed

        if (txtMaMH.getText().trim().isEmpty() || txtTenMH.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ Mã Môn Học và Tên Môn Học!");
            return;
        }

        MonHoc mh = Gan_Du_LieuMH();

        if (monHocDao.insert(mh)) {
            JOptionPane.showMessageDialog(this, "Thêm Môn Học thành công!");
            Khoi_Tao_TableMH();
            btnLamMoiActionPerformed(null);
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại! Mã Môn Học có thể đã tồn tại.");
        }
    }//GEN-LAST:event_btnThemMHActionPerformed

    private void btnSuaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaMHActionPerformed
        int chi_so_dong = TblMonHoc.getSelectedRow();
        String maMH = txtMaMH.getText().trim();
        if (chi_so_dong < 0 && maMH.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa hoặc nhập Mã Môn Học để Sửa!");
            return;
        }

        MonHoc mh = Gan_Du_LieuMH();

        if (monHocDao.update(mh)) {
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin Môn Học thành công!");
            Khoi_Tao_TableMH();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
        }
    }//GEN-LAST:event_btnSuaMHActionPerformed

    private void TblMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblMonHocMouseClicked
        int row = TblMonHoc.getSelectedRow();

        if (row >= 0) {

            String MaMH = TblMonHoc.getValueAt(row, 0).toString();
            String TenMH = TblMonHoc.getValueAt(row, 1).toString();
            int SoTC = (int) TblMonHoc.getValueAt(row, 2);
            txtMaMH.setText(MaMH);
            txtTenMH.setText(TenMH);
            txtstc.setText(String.valueOf(SoTC));

    }//GEN-LAST:event_TblMonHocMouseClicked
    }
    private void tblDangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDangKyMouseClicked
     int row = tblDangKy.getSelectedRow();

        if (row >= 0) {

            String MaSV = tblDangKy.getValueAt(row, 0).toString();
            String MaMH = tblDangKy.getValueAt(row, 1).toString();
            String strNgay = tblDangKy.getValueAt(row, 2).toString();
            double diemQT = (double) tblDangKy.getValueAt(row, 3);
            double diemThi = (double) tblDangKy.getValueAt(row, 4);
            double diemTK = (double) tblDangKy.getValueAt(row, 5);
            txtMaSVDK.setText(MaSV);
            txtMaMHDK.setText(MaMH);
          
            txtDiemQT.setText(String.valueOf(diemQT));
             txtDiemThi.setText(String.valueOf(diemThi));
              txtDiemTK.setText(String.valueOf(diemTK));
              
               //chuyển đổi kiểu ngày tháng
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                Date ngaySinh = sdf.parse(strNgay);
                dtcNgayDK.setDate(ngaySinh);
            } catch (Exception e) {
                dtcNgayDK.setDate(null);
            }
    }//GEN-LAST:event_tblDangKyMouseClicked
}
    private void btnThemDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDKActionPerformed
 //  Kiểm tra các ô Text rỗng
        if (txtMaSVDK.getText().trim().isEmpty() || txtMaMHDK.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ Mã SV và Mã Môn Học!");
            return; // Dừng hàm ngay lập tức
        }

        //  Kiểm tra Ngày sinh rỗng 
        if (dtcNgayDK.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Ngày Đăng ký!");
            return; // Dừng hàm
        }

      

        // Nếu tất cả đều hợp lệ mới tạo đối tượng và chèn vào CSDL
        DangKy dk = Gan_Du_LieuDK();

        if (dangKyDao.insert(dk)) {
            JOptionPane.showMessageDialog(this, "Đăng Ký thành công!");
            Khoi_Tao_TableDK();
            btnLamMoiActionPerformed(null);
        } else {
            JOptionPane.showMessageDialog(this, "Đăng Ký thất bại");
        }        
    }//GEN-LAST:event_btnThemDKActionPerformed

    private void btnXoaDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDKActionPerformed
       
        String maSV = txtMaSVDK.getText().trim();
    

        int chi_so_dong = tblDangKy.getSelectedRow();
         if (chi_so_dong < 0 && maSV.isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng hoặc nhập Mã sinh viên cần Xóa !");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn xóa sinh viên: [" + maSV + "]" + " không?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            if (dangKyDao.delete(maSV)) {
                JOptionPane.showMessageDialog(this, "Xóa sinh viên thành công!");
                Khoi_Tao_TableDK();
                btnLamMoiActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            } 
    }//GEN-LAST:event_btnXoaDKActionPerformed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Áp dụng giao diện macOS Sáng (Light Mode)
            com.formdev.flatlaf.themes.FlatMacLightLaf.setup();

            // (Tùy chọn) Bo tròn viền nút bấm & ô nhập liệu chuẩn macOS
            javax.swing.UIManager.put("Component.arc", 10);
            javax.swing.UIManager.put("Button.arc", 10);
            javax.swing.UIManager.put("TextComponent.arc", 8);

        } catch (Exception ex) {
            System.err.println("Lỗi nạp Look and Feel macOS");
        }

        /* Hiển thị Form */
        java.awt.EventQueue.invokeLater(() -> {
            new SinhVienForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadNu;
    private javax.swing.JTable TblMonHoc;
    private javax.swing.ButtonGroup btgGioiTinh;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLamMoiDK;
    private javax.swing.JButton btnLamMoiKH;
    private javax.swing.JButton btnLamMoiMH;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSuaDK;
    private javax.swing.JButton btnSuaKH;
    private javax.swing.JButton btnSuaMH;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemDK;
    private javax.swing.JButton btnThemKH;
    private javax.swing.JButton btnThemMH;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThoatDK;
    private javax.swing.JButton btnThoatKH;
    private javax.swing.JButton btnThoatMH;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaDK;
    private javax.swing.JButton btnXoaKH;
    private javax.swing.JButton btnXoaMH;
    private javax.swing.JComboBox<String> cboKhoa;
    private com.toedter.calendar.JDateChooser dtcNgayDK;
    private com.toedter.calendar.JDateChooser dtcNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JPanel tabDangKy;
    private javax.swing.JPanel tabKhoa;
    private javax.swing.JPanel tabSinhVien;
    private javax.swing.JPanel tabmonhoc;
    private javax.swing.JTable tblDangKy;
    private javax.swing.JTable tblKhoa;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDiemQT;
    private javax.swing.JTextField txtDiemTK;
    private javax.swing.JTextField txtDiemThi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaMH;
    private javax.swing.JTextField txtMaMHDK;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtMaSVDK;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenMH;
    private javax.swing.JTextField txtstc;
    // End of variables declaration//GEN-END:variables

    private void Khoi_Tao_ComboBox() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboKhoa.getModel();
        model.removeAllElements();

        List<Khoa> listKhoa = khoaDao.findAll();
        for (Khoa k : listKhoa) {
            model.addElement(k);
        }
    }

    private void Khoi_Tao_Table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("MaSV");
        model.addColumn("HoTen");
        model.addColumn("NgaySinh");
        model.addColumn("GioiTinh");
        model.addColumn("DiaChi");
        model.addColumn("MaKhoa");

        JTable table = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(table);
        model.setRowCount(0);

        model = (DefaultTableModel) tblSinhVien.getModel();

        model.setColumnIdentifiers(new Object[]{
            "Mã SV", "Họ tên", "Ngày sinh", "Giới tính", "Địa chỉ", "Mã khoa"
        });

        model.setRowCount(0);

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");

        List<SinhVien> list = sinhVienDao.findAll();
        for (SinhVien sv : list) {
            String strNgaySinh = (sv.getNgaySinh() != null) ? sdf.format(sv.getNgaySinh()) : "";
            String strGioiTinh = sv.isGioiTinh() ? "Nam" : "Nữ";

            model.addRow(new Object[]{
                sv.getMaSV(),
                sv.getHoTen(),
                strNgaySinh,
                strGioiTinh,
                sv.getDiaChi(),
                sv.getMaKhoa()
            });
        }
    }

    private SinhVien Gan_Du_lieu() {
        String maSV = txtMaSV.getText().trim();
        String hoTen = txtHoTen.getText().trim();

        // Kiểm tra ngày tháng
        Date ngaySinh = (dtcNgaySinh.getDate() != null) ? dtcNgaySinh.getDate() : new Date();

        boolean gioiTinh = radNam.isSelected();
        String diaChi = txtDiaChi.getText().trim();

        // Kiểm tra ComboBox
        String maKhoa = "";
        if (cboKhoa.getSelectedItem() != null) {
            if (cboKhoa.getSelectedItem() instanceof Khoa) {
                Khoa k = (Khoa) cboKhoa.getSelectedItem();
                maKhoa = k.getMaKhoa();
            } else {
                maKhoa = cboKhoa.getSelectedItem().toString();
            }
        }
        return new SinhVien(maSV, hoTen, ngaySinh, gioiTinh, diaChi, maKhoa);
    }

    private void Chon_Khoa(String maKhoa) {
        for (int i = 0; i < cboKhoa.getItemCount(); i++) {
            Object item = cboKhoa.getItemAt(i);

            if (item instanceof Khoa) {
                Khoa k = (Khoa) item;
                if (k.getMaKhoa().equalsIgnoreCase(maKhoa)) {
                    cboKhoa.setSelectedIndex(i);
                    return;
                }
            } else if (item.toString().equalsIgnoreCase(maKhoa)) {
                cboKhoa.setSelectedIndex(i);
                return;
            }
        }
    }

    private void Khoi_Tao_TableKH() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("MaKhoa");
        model.addColumn("TenKhoa");

        JTable table = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(table);
        model.setRowCount(0);

        model = (DefaultTableModel) tblKhoa.getModel();

        model.setColumnIdentifiers(new Object[]{
            "Mã Khoa", "Tên Khoa"
        });

        model.setRowCount(0);

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");

        KhoaDao khoaDao = new KhoaDao();
        List<Khoa> list = khoaDao.findAll();
        for (Khoa kh : list) {

            model.addRow(new Object[]{
                kh.getMaKhoa(),
                kh.getTenKhoa(),});
        }
    }

    private Khoa Gan_Du_LieuKH() {
        String maKhoa = txtMaKH.getText().trim();
        String tenKhoa = txtTenKH.getText().trim();

        return new Khoa(maKhoa, tenKhoa);
    }

    private void Khoi_Tao_TableMH() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("MaMH");
        model.addColumn("TenMH");
        model.addColumn("SOTinChi");

        JTable table = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(table);
        model.setRowCount(0);

        model = (DefaultTableModel) TblMonHoc.getModel();

        model.setColumnIdentifiers(new Object[]{
            "Mã Môn Học", "Tên Môn Học", "Số Tín Chỉ"
        });

        model.setRowCount(0);

        List<MonHoc> list = monHocDao.findAll();
        for (MonHoc mh : list) {

            model.addRow(new Object[]{
                mh.getMaMH(),
                mh.getTenMH(),
                mh.getSoTC()

            });
        }
    }

    private MonHoc Gan_Du_LieuMH() {
        String maMH = txtMaMH.getText().trim();
        String tenMH = txtTenMH.getText().trim();
        int soTC = Integer.parseInt(txtstc.getText().trim());

        return new MonHoc(maMH, tenMH, soTC);
    }

    private void Khoi_Tao_TableDK() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("MaSV");
        model.addColumn("MaMH");
        model.addColumn("NgayDangKy");
        model.addColumn("DiemQuaTrinh");
        model.addColumn("DiemThi");
        model.addColumn("DiemTongKet");

        JTable table = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(table);
        model.setRowCount(0);

        model = (DefaultTableModel) tblDangKy.getModel();

        model.setColumnIdentifiers(new Object[]{
            "Mã SV", "Mã Môn Học", "Ngày Đăng Ký", "Điểm Quá Trình", "Điểm Thi", "Điểm Tổng Kết"
        });

        model.setRowCount(0);

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");

        List<DangKy> list = dangKyDao.findAll();
        for (DangKy dk : list) {
            String strNgayDK = (dk.getNgayDK() != null) ? sdf.format(dk.getNgayDK()) : "";

            model.addRow(new Object[]{
                dk.getMaSVDK(),
                dk.getMaMHDK(),
                strNgayDK,
                dk.getDiemQT(),
                dk.getDiemThi(),
                dk.getDiemTK()
            });
        }
    }

    private DangKy Gan_Du_LieuDK() {
        String maSV = txtMaSVDK.getText().trim();
        String maMH = txtMaMHDK.getText().trim();

        // Kiểm tra ngày tháng
        Date ngayDK = (dtcNgayDK.getDate() != null) ? dtcNgayDK.getDate() : new Date();
        double diemQT = Double.parseDouble(txtDiemQT.getText().trim());
       double diemThi = Double.parseDouble(txtDiemThi.getText().trim());
       double diemTK = Double.parseDouble(txtDiemTK.getText().trim());
       
        return new DangKy(maSV, maMH, ngayDK, diemQT, diemThi, diemTK);

    }

}
